### ISSUE TITLE
ヘッダー

### ISSUE THREAD

**Issue by Shinya-Takiyoshi** [Shinya-Takiyoshi/RentalBookApp#18]
ヘッダーphpを切り出しているが、layouts.appにマージして使えるようにする。
ヘッダーphpを使用していた箇所はlayouts.appに修正して統一する。

- [x] 1.初期表示
- [x] 2.ログインリンク押下時
- [x] 3.新規登録リンク押下時
- [x] 4.マイページリンク押下時
- [x] 5.お知らせリンク押下時
- [x] 6.HOMEリンク押下時

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
middlewareで対応した時に取得した情報を画面に返そうとしましたが、画面に到達しなかったため、sessionに取得したお知らせの配列を格納してお知らせ表示するように実装しました。
他にいい案ありますか？

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
なるほど。middlewareで定義したお知らせの配列を画面に表示できればいいと言うことですか？
その場合、mergeメソッドを使えばできるみたいです。
middlewareからcontrollerへ値を渡すイメージです。
https://qiita.com/hosikiti/items/bd23fdbf973527a24207

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
ありがとうございます。
request->merge()は既に試していました。
この場合、各Controllerで受け取り、画面に渡す処理を加える必要があるため、辞めました。

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
hiddenだと共通的に情報表示が難しかったので、単純に必要なお知らせの情報をsessionに格納して取得するように変更しました。
設計書とは実装が異なっています。

**Comment by JinKanekama** [comment]
> @JinKanekama
> ありがとうございます。
> request->merge()は既に試していました。
> この場合、各Controllerで受け取り、画面にrequest->merge()で取得したお知らせ情報を渡す処理を加える必要があるため、辞めました。
> デメリット：コード量が多くなる、各Controllerで処理を書き忘れた場合に動かない

@Shinya-Takiyoshi 
なるほど。了解しました。
もっと調べてみると、View::shareでミドルウェア上でviewで使える変数が定義できるみたいです。

> @JinKanekama
> hiddenだと共通的に情報表示が難しかったので、単純に必要なお知らせの情報をsessionに格納して取得するように変更しました。
> 設計書とは実装が異なっています。
> 今週話しましょう

了解です。

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
https://qiita.com/kenichi-arita/items/099851053bfff5402828

**Comment by Shinya-Takiyoshi** [comment]
> @Shinya-Takiyoshi
> https://qiita.com/kenichi-arita/items/099851053bfff5402828
> 
> https://qiita.com/kazuhei/items/7de36d5aab440b3f5928

ViewFactoryを採用
理由：
①View::Shareはプロバイダ登録が必要(公式調べ)
②掲載されているqiitaのView::Shareの記事が　2016年と古い
③ViewFactoryはView::Shareに比べてmiddleware内だけ完結できる利点がある。

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
相談。お知らせ表示で、既に削除されてしまった図書情報にアクセスした場合、対応はどうしますか？
①お知らせ情報と図書情報を比較して取得できたもののみ表示する(図書情報が確実にあるもの)
②図書情報が既に削除されているものについては、「この本は削除されています」などの警告ページに誘導しアナウンスをする。
備考：①の方が結合するだけなので工数はかからない。

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
①の対応でいきましょう。あと、もしかしたら、お知らせテーブルと図書テーブルをリレーションで繋いでたら、図書削除の際にお知らせも自動で消えるかもしれません。

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
返答ありがとうございます。
リレーション繋いで確認してみますね！

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
図書削除はexists使って取得時に絞るようにしました。

**Comment by Shinya-Takiyoshi** [comment]
routeだとお知らせフラグを落とすときの必要なパラメータ多いね。

**Comment by Shinya-Takiyoshi** [comment]
TODO:登録日時、更新日時がおかしい件について修正
@JinKanekama 
そちらのmysqlでは現在日時になっている？？

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
bookテーブルのcreated_atとupdated_atがnullになる問題を解決したんですが、それですか？

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama それとは別な気がします。会議のとき話しましょう

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
laravelのtimezoneを変更することで解決しました。
https://qiita.com/pinkumohikan/items/2e9cefb85d75a8622d99

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
ありがとうございます!

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
ヘッダーの色はこちらでお願いします。
#2dd354
