### ISSUE TITLE
開発_図書詳細

### ISSUE THREAD

**Issue by Shinya-Takiyoshi** [Shinya-Takiyoshi/RentalBookApp#2]
- [x] 1.初期表示
- [x] 2.コメント確定ボタン押下時
- [x] 3.レンタル申し込みボタン押下時
- [x] 4.レンタル終了ボタン押下時
- [x] 5.コメント削除ボタン押下時

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
ログインユーザーと図書の貸出人が一致しない場合
　図書が貸出可能な場合
　　レンタル申し込みボタンを表示、レンタル終了ボタンを非表示
上記で対応しますが、未ログイン時のレンタル申し込みボタンへの遷移は可能にしますか？
ログインに飛ばすようにしますか？

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
ログインユーザー分岐する初期処理のボタン表示について
レンタル申し込みボタン、レンタル終了ボタンが同時に表示するケースは存在しない？(確認)

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 

> 上記で対応しますが、未ログイン時のレンタル申し込みボタンへの遷移は可能にしますか？
ログインに飛ばすようにしますか？

未ログイン時はレンタル申し込みボタンは非表示にします。

**Comment by Shinya-Takiyoshi** [comment]
2020/06/20　会議にて相談　備忘録
```
図書詳細　実装　相談
非活性と非表示分けてると思いますが、非表示で統一した方がやりやすいです。
理由を聞きたい。
 →最初検討：活性/非活性
　2回目検討:表示/非表示
　上記が混ざったため、統一されていない。
    　決定事項：
　    →表示/非表示に統一する。
　    →コメント+ボタンの非表示処理を追加する。

現段階の検討
laravelからjsへ値を渡し、js上でDOM操作をする。
https://qiita.com/ntm718/items/638a8f56d30d047ead0f
```

**Comment by Shinya-Takiyoshi** [comment]
> @Shinya-Takiyoshi
> 
> > 上記で対応しますが、未ログイン時のレンタル申し込みボタンへの遷移は可能にしますか？
> > ログインに飛ばすようにしますか？
> 
> 未ログイン時はレンタル申し込みボタンは非表示にします。もし、レンタル申し込みのurlに飛んだ場合は、ログイン画面に飛ぶようにします。
> 
> > レンタル申し込みボタン、レンタル終了ボタンが同時に表示するケースは存在しない？(確認)
> 
> はい、その認識であってます。

@JinKanekama 
承知いたしました。引き続き対応いたします。

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
これ来期に検討ですが
コメント削除時にuser_idによって削除可と不可にできる機能つけた方がいいのかなと。
あとはレンタル開始したらコメントを削除できなくする機能。

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
なるほど。現状だとログインユーザーならだれでも削除できるようになってますよね。
それだとよくないので、図書の所有者のみ削除できるのが理想です。

その要件も採用します。

**Comment by JinKanekama** [comment]
コメント欄の仕様変更
非ログインユーザーには非表示
→非ログインユーザーはコメント欄の閲覧は可。コメントの操作は不可。

**Comment by Shinya-Takiyoshi** [comment]
対応完了
