### ISSUE TITLE
開発_図書編集

### ISSUE THREAD

**Issue by JinKanekama** [Shinya-Takiyoshi/RentalBookApp#26]
- [x] 1.初期表示
- [x] 2. アップロード処理
- [x]  3.例外処理

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
マイルストーンの割り当てですが、管理者ユーザーでないと出来なさそうなので、このissueを割り当ててもらえますか？

**Comment by Shinya-Takiyoshi** [comment]
OKです。割り当てました
