### ISSUE TITLE
開発_マイページ

### ISSUE THREAD

**Issue by Shinya-Takiyoshi** [Shinya-Takiyoshi/RentalBookApp#3]
- [x] 1.初期表示
- [x] 2マイブックリンク押下時
- [x] 3.貸している本リンク押下時
- [x] 4.借りている本リンク押下時
- [x] 5.アップロードリンク押下時
- [x] 6.編集ボタン押下時
- [x] 7.削除ボタン押下時

**Comment by Shinya-Takiyoshi** [comment]
相談。
ルーティングについて、各ボタン分けるか。
分ける場合、それぞれリクエストに対応したメソッドの用意が必要なため、単純にはなるがコード量が増える。
分けない場合、処理がまとまっているが、ユーザビリティを考えたときにurlが変化していないことに本当にボタンを押せているのかがわからない

**Comment by Shinya-Takiyoshi** [comment]
ボタンはリンクへ。処理ごとにメソッドは分ける

**Comment by Shinya-Takiyoshi** [comment]
前処理にユーザー情報取得を実装する予定なので下記を調べた。
コンストラクタにある$this->middleware('auth');の内容。
ログイン情報の保持はしているが保持しているidは、トークンに近いため別で前処理でユーザーIDを取得する。
https://qiita.com/darum/items/d53924177a7285a5c152

**Comment by Shinya-Takiyoshi** [comment]
未着手としているもの
①ユーザー情報の取得方法
　セッションを検討中
②異常終了時のエラーページへの遷移

**Comment by JinKanekama** [comment]
図書削除に関して、追加要件があります。
要件：図書削除時にrental_statusが１のものは削除できないようにする
理由：レンタルが開始されたら終了するまで図書の削除はできないようにしてほしいから

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
追加要件について承知しました。

**Comment by Shinya-Takiyoshi** [comment]
追加要件対応完了
