### ISSUE TITLE
開発_図書アップロード

### ISSUE THREAD

**Issue by Shinya-Takiyoshi** [Shinya-Takiyoshi/RentalBookApp#4]
- [x] 1.初期表示

- [x] 2. アップロード処理

- [x] 3.例外処理

**Comment by Shinya-Takiyoshi** [comment]
insert処理で気をつけること
https://teratail.com/questions/150158

**Comment by JinKanekama** [comment]
- [ ] 1.アップロードボタン押下時

**Comment by JinKanekama** [comment]
LaravelのJavascriptのファイルを配置する方法
https://qiita.com/ntm718/items/fed0e1060557a4e28ef3

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
動かしてみました。
BookUploadController.save()
$resultについて初期値は設定しておいた方がいいですね。
次回コミット時に修正お願いします。

**Comment by JinKanekama** [comment]
- [ ] 1.初期表示

- [ ] 2. アップロード処理

- [ ] 3.例外処理

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
設計で考慮漏れたのですが、
例外発生時に画像ファイルを削除する処理が抜けてました。
そうしないと、例外は起きたけど、ファイルは保存されるという中途半端な状態が発生します。

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
タスクリストは一番上である必要があるため、移動しました。よろしくお願いします。

**Comment by Shinya-Takiyoshi** [comment]
エラー起きています。
<img width="1440" alt="スクリーンショット 2020-06-20 20 42 33" src="https://user-images.githubusercontent.com/12153970/85202279-38c5fe00-b340-11ea-8c3f-0ded4888a568.png">

useを直接指定することでエラーは消えますが、環境差分が出ていると思われる。
原因解消に詰まったため、保留とする。
[
<img width="1440" alt="スクリーンショット 2020-06-20 21 47 42" src="https://user-images.githubusercontent.com/12153970/85202309-73c83180-b340-11ea-89a3-5e9923b05cf5.png">
](url)
