### ISSUE TITLE
開発_新規登録

### ISSUE THREAD

**Issue by Shinya-Takiyoshi** [Shinya-Takiyoshi/RentalBookApp#6]
- [x] 1.初期表示

- [x] 2.登録ボタン押下時

**Comment by JinKanekama** [comment]
- [ ] 1.初期表示

- [ ] 2.登録ボタン押下時

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
新規登録後のユーザーidのセッションがうまくいっていない。新規登録→ログイン処理がうまくいっていない？？
再度ログインページからログインすると、表示できる。

再現方法：
①userテーブル0→画面アクセス。
②新規登録する。
③ページが404になる。
理由：おそらくsessionからuser情報が取得できていないため

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
一番上のタスクのチェック（2の方）をお願いします。

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
新規登録からの画面遷移を確認しました。
現状、新規登録後、/mypageにいくことになっていますが、/mypageのルートは現在存在しないため、エラーになっていると思われます。
RouteServiceProvider.phpファイルを修正。登録完了した場合の画面遷移を/mypage→/mypage/selectMyBookListに修正、
動作確認OK

**Comment by Shinya-Takiyoshi** [comment]
なるほど。忘れていた。ありがとう！
