### ISSUE TITLE
開発_ログイン

### ISSUE THREAD

**Issue by Shinya-Takiyoshi** [Shinya-Takiyoshi/RentalBookApp#7]
- [x] 1.初期表示

- [x] 2.ログインボタン押下時

**Comment by Shinya-Takiyoshi** [comment]
ログイン後にセッションに取得したidを保持したい

**Comment by JinKanekama** [comment]
Auth::user()でログインしているユーザーの情報を取得できる

**Comment by Shinya-Takiyoshi** [comment]
これってdbから取得していませんか？
実現したかったことはDBから取得せず、sessionで管理することです。
理由:DBアクセスを極力減らすため

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
そうですね。ログイン処理の後ミドルウェアでセッションに登録する感じでしょうか。

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
PHPにおけるセッション管理にしてもいろいろな方法があるんですね。
https://qiita.com/SuguruOoki/items/6ca36ad1d366df6c98af

**Comment by JinKanekama** [comment]
Laravel の Guard（認証）について
https://qiita.com/tomoeine/items/40a966bf3801633cf90f

**Comment by JinKanekama** [comment]
- [ ] 初期表示

- [ ] アップロード処理

- [ ] 例外処理

**Comment by JinKanekama** [comment]
- [ ] 1.初期表示

- [ ] 2.ログインボタン押下時

**Comment by JinKanekama** [comment]
"remember me" cookieを使って認証
http://recipes.laravel.jp/recipe/86

**Comment by JinKanekama** [comment]
viarember()メソッドが使えない場合、authcheckメソッドでログイン認証がtrueでセッションがない場合、
Authでuser_idなどを再取得し、sessionの設定をし直す。

**Comment by JinKanekama** [comment]
> * [ ]  1.初期表示
> * [ ]  2.ログインボタン押下時

両方のチェックお願いします。

**Comment by Shinya-Takiyoshi** [comment]
@JinKanekama 
チェック入れました。
このチェックについては進捗時の確認でもいいかもね。

**Comment by JinKanekama** [comment]
@Shinya-Takiyoshi 
了解しました。
